version: '3'

services:
  expenses-db:
    image: postgres:16.2-alpine3.19
    container_name: expenses-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: expenses
      POSTGRES_PASSWORD: passw0rd
      POSTGRES_DB: expenses
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      expenses:
        ipv4_address: 172.18.0.2

networks:
  expenses:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/16"
volumes:
  postgres_data:
    driver: local
