version: '3.8'
networks:
  mynetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.19.0.0/16"
services:
  generator-1:
    image: dali/generator:latest
    restart: always
    ports:
      - '8001:8000'
    volumes:
      - app1:/app
    networks:
      mynetwork:
        ipv4_address: 172.19.0.2
  generator-2:
    image: dali/generator:latest
    restart: always
    ports:
      - '8002:8000'
    volumes:
      - app2:/app
    networks:
      mynetwork:
        ipv4_address: 172.19.0.3
volumes:
  app1:
    driver: local
  app2:
    driver: local
