version: '3'

services:
  mongo:
    image: mongo
    container_name: store-db
    ports:
      - "27017:27017"
    volumes:
      - /home/dali/WORK/work02/_store_data:/data/db
    networks:
      finops:
        ipv4_address: 172.18.0.2

volumes:
  _store_data:
    driver: local

networks:
  finops:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/16"
