version: '3'

networks:
  datapipeline:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/16"

services:
  analytics-db:
    image: postgres:16.2-alpine3.19
    container_name: analytics-db
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=analytics
      - POSTGRES_USER=analytics
      - POSTGRES_DB=analytics
    networks:
      datapipeline:
        ipv4_address: 172.18.0.2
