app:
  name: finops
  version: 1.0.0  
clients:
- client_name: momentum tech
  cloud_name: aws
  account_name: momentumtech
  access_key_id: AKIAVLD2GWDASFY3WNLY
  secret_access_key_name: secret-aws-momentumtech
  region: ca-central-1