version: '3'
services:
  # database service for analytics service
  analytics-db-service:
    build:
      context: ./analytics/analytics-db-service
      dockerfile: Dockerfile
    container_name: analytics-db-service
    hostname: analytics_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 1s
      retries: 5
    secrets:
      - analytics-db-pass
    environment:
      POSTGRES_DB: analytics
      POSTGRES_USER: admin
      POSTGRES_PASSWORD_FILE: /run/secrets/analytics-db-pass
    ports:
      - '5432:5432'
    volumes:
      - analytics-db-service-VL:/var/lib/postgresql/data

volumes:
  analytics-db-service-VL:


secrets:
  analytics-db-pass:
    file: analytics-db-service/pass.txt
