version: '3'

services:
  finops-db:
    image: postgres:16.2-alpine3.19
    container_name: finops-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: finops
      POSTGRES_PASSWORD: passw0rd
      POSTGRES_DB: finops
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      finops:
        ipv4_address: 172.18.0.2

networks:
  finops:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/16"
volumes:
  postgres_data:
    driver: local
