app:
  name: finops
  version: 1.0.0
clients:
- client_name: Quantum Innovations
  client_code: quantuminnovations
  cloud_name: aws
  account_id: '323625553814'
  account_seed: '1'
  fake_data: true
- client_name: Quantum Innovations
  client_code: quantuminnovations
  cloud_name: azure
  subscription: subscription 1
  account_seed: '12'
  fake_data: true  