app:
  name: finops
  version: 1.0.0
  key-vault-name: finops-keyvault5
clients:
- client_name: Quantum Innovations
  client_code: quantuminnovations
  cloud_name: aws
  account_name: momentum-test
  access_key_id: 1111111111
  secret_access_key: secret-momentum-test