version: '3'
networks:
  datapipeline:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/16"

services:
  spark-master:
    image: bitnami/spark:3.3.1
    hostname: spark-master
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    ports:
      - '8080:8080'
      - '7077:7077'
    volumes:
      - ./data:/data
      - ./src:/src
    networks:
      datapipeline:
        ipv4_address: 172.18.0.2

  spark-worker:
    image: bitnami/spark:3.3.1
    hostname: spark-worker
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_EXECUTOR_MEMORY=4G
      - SPARK_WORKER_CORES=4
    ports:
      - '8081:8081'
    volumes:
      - ./data:/data
      - ./src:/src
    networks:
      datapipeline:
        ipv4_address: 172.18.0.3

  jupyter:
    image: jupyter/pyspark-notebook:spark-3.3.1
    hostname: jupyter
    container_name: jupyter
    ports:
      - '8890:8888'
    volumes:
      - ./notebooks:/home/jovyan/work/notebooks
      - ./data:/home/jovyan/work/data
    networks:
      datapipeline:
        ipv4_address: 172.18.0.4

  generator:
    image: dali/generator:latest
    hostname: generator
    container_name: generator
    restart: always
    ports:
      - "8000:8000"
    networks:
      datapipeline:
        ipv4_address: 172.18.0.100
